#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🚀 Amadeus MCP Server Setup');
console.log('============================\n');

console.log('To use this MCP server, you need Amadeus API credentials.');
console.log('Get them from: https://developers.amadeus.com/\n');

const envPath = path.join(__dirname, '.env');
const envExamplePath = path.join(__dirname, 'env.example');

// Check if .env already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env file already exists. Do you want to overwrite it? (y/N)');
  rl.question('', (answer) => {
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
      createEnvFile();
    } else {
      console.log('Setup cancelled. Your existing .env file remains unchanged.');
      rl.close();
    }
  });
} else {
  createEnvFile();
}

function createEnvFile() {
  console.log('\nPlease enter your Amadeus API credentials:\n');
  
  rl.question('Amadeus Client ID: ', (clientId) => {
    rl.question('Amadeus Client Secret: ', (clientSecret) => {
      rl.question('Environment (test/live) [test]: ', (environment) => {
        environment = environment || 'test';
        
        const envContent = `# Amadeus API Configuration
# Generated by setup script

AMADEUS_CLIENT_ID=${clientId}
AMADEUS_CLIENT_SECRET=${clientSecret}
AMADEUS_ENVIRONMENT=${environment}
LOG_LEVEL=info
`;
        
        try {
          fs.writeFileSync(envPath, envContent);
          console.log('\n✅ .env file created successfully!');
          console.log('🚀 You can now run: npm start');
        } catch (error) {
          console.error('❌ Error creating .env file:', error.message);
        }
        
        rl.close();
      });
    });
  });
}

rl.on('close', () => {
  process.exit(0);
});
